version: '3.9'

services:
  postgres:
    image: postgres:16.4-alpine
    container_name: postgresql-for-taberuu
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taberuu_db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: pgadmin4-for-postgresql
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - '5050:80'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  mongo:
    image: mongo:7.0.12-jammy
    container_name: mongo-for-taberuu
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=securepassword123
      - MONGO_INITDB_DATABASE=taberuu_db
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-data/log:/var/log/mongodb/

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-for-taberuu
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://root:securepassword123@mongo:27017/
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo
