import { User } from '@src/context/users/domain/user';

export const users: User[] = [
  new User({
    id: '4d542802-a9db-4606-ab33-5bfdda9686c4',
    name: 'Mike',
    lastname: 'Runolfsson',
    email: 'Claudine.Kerluke87@taberuuapp.com',
    password: 'securePassword123',
    profileImage: 'https://avatars.githubusercontent.com/u/93068632',
    phoneNumber: null,
    phoneCode: null,
    role: 'ADMIN',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  }),
  new User({
    id: '38d07279-a74b-4335-b3d0-43b441f2551b',
    name: 'Arlene',
    lastname: 'Medhurst',
    email: 'Aubree92@taberuuapp.com',
    password: 'securePassword123',
    profileImage: 'https://avatars.githubusercontent.com/u/45533641',
    phoneNumber: null,
    phoneCode: null,
    role: 'ADMIN',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  }),
  new User({
    id: '0fe9acaa-7424-4d4f-99bf-34e364c384ca',
    name: 'Demarcus',
    lastname: 'Schmeler',
    email: 'Carissa93@taberuuapp.com',
    password: 'securePassword123',
    profileImage: 'https://avatars.githubusercontent.com/u/13679853',
    phoneNumber: null,
    phoneCode: null,
    role: 'ADMIN',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  }),
  new User({
    id: '13194004-1052-4a3e-b7c5-9a69b4a86c43',
    name: 'Raphael',
    lastname: 'Bode',
    email: 'Alyson_Jones67@taberuuapp.com',
    password: 'securePassword123',
    profileImage: 'https://avatars.githubusercontent.com/u/98066605',
    phoneNumber: null,
    phoneCode: null,
    role: 'ADMIN',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  }),
  new User({
    id: '26a64a2c-0edf-4475-9d4e-f3d4afb16de5',
    name: 'Danyka',
    lastname: 'Mann',
    email: 'Charlotte_Powlowski20@taberuuapp.com',
    password: 'securePassword123',
    profileImage: 'https://avatars.githubusercontent.com/u/1234371',
    phoneNumber: null,
    phoneCode: null,
    role: 'ADMIN',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  }),
  new User({
    id: '6b609436-103b-44c9-9caf-7a632e67f6c1',
    name: 'Maverick',
    lastname: 'Olson',
    email: 'Myrtis20@taberuuapp.com',
    password: 'securePassword123',
    profileImage: 'https://avatars.githubusercontent.com/u/98555286',
    phoneNumber: null,
    phoneCode: null,
    role: 'ADMIN',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  }),
  new User({
    id: 'b0cd487a-a5bd-49f4-b182-bc607de7faec',
    name: 'Lauren',
    lastname: 'Rachel',
    email: 'Rubye_Bayer@taberuuapp.com',
    password: 'securePassword123',
    profileImage: 'https://avatars.githubusercontent.com/u/50597587',
    phoneNumber: null,
    phoneCode: null,
    role: 'ADMIN',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  }),
  new User({
    id: 'c307f0fe-9b20-4eb5-8a3d-96582ca1c871',
    name: 'Camilla',
    lastname: 'Christiansen',
    email: 'Presley_Conroy27@taberuuapp.com',
    password: 'securePassword123',
    profileImage: 'https://avatars.githubusercontent.com/u/98736086',
    phoneNumber: null,
    phoneCode: null,
    role: 'ADMIN',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  }),
  new User({
    id: '8d79e923-303f-408a-bc02-4e709d9e19b9',
    name: 'Eden',
    lastname: 'Schmidt',
    email: 'Tobin_Price@taberuuapp.com',
    password: 'securePassword123',
    profileImage: 'https://avatars.githubusercontent.com/u/62730877',
    phoneNumber: null,
    phoneCode: null,
    role: 'ADMIN',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  }),
  new User({
    id: '7f5b1a35-ac9d-451d-8eed-5e819327b790',
    name: 'Wellington',
    lastname: 'Grady',
    email: 'Gerard50@taberuuapp.com',
    password: 'securePassword123',
    profileImage: 'https://avatars.githubusercontent.com/u/71108468',
    phoneNumber: null,
    phoneCode: null,
    role: 'ADMIN',
    createdAt: new Date(),
    updatedAt: null,
    deletedAt: null,
  }),
];
