export enum Roles {
  RESTAURANT_OWNER = 'RESTAURANT_OWNER',
  MENU_EDITOR = 'MENU_EDITOR',
  SUPERVISOR = 'SUPERVISOR',
  ADMIN = 'ADMIN',
  CUSTOMER = 'CUSTOMER',
  DELIVERY_DRIVER = 'DELIVERY_DRIVER',
}
