name: Unit Test

on:
  push:
    branches:
      - 'feature/**'
      - 'bug/**'
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm lint

      - name: Format code
        run: pnpm format

      - name: Build application
        run: pnpm build

      - name: Run Unit Tests
        run: pnpm test

      - name: Check Jest configuration
        run: cat jest.config.ts

      - name: Run Tests with Coverage
        run: pnpm test:cov
